### ISSUE TITLE
mockrepo dan mocksharedrepo tidak di buat saat init service

### ISSUE THREAD

**Issue by zgunz42** [golangid/candi#10]
Ada beberapa test file yang di buat sama cli tapi mock tidak dibuat oleh cli
```
	mockrepo "monorepo/services/auth/pkg/mocks/modules/token/repository"
	mocksharedrepo "monorepo/services/auth/pkg/mocks/shared/repository"
```
file yang di atas sudah coba cari di dalam folder juga tidak ada

**Comment by agungdwiprasetyo** [comment]
betul, jadi tidak disertakan ketika generate code2nya karena mocknya sendiri hasil generate juga dari https://github.com/vektra/mockery (bisa dibaca di readme hasi generatenya)
