### ISSUE TITLE
TaskQueueWorker tidak berjalan secara default ketika menggunakan MariaDB

### ISSUE THREAD

**Issue by isogram** [golangid/candi#29]
Ketika menggunakan **TaskQueueWorker** dan memilih **MariaDB** sebagai databasenya, **secara default tidak bisa jalan**. Begini errornya,

![image](https://github.com/golangid/candi/assets/3049864/e85cb44f-c50a-4710-80ac-4fe36bd53f55)

Sepertinya ini terkait dengan query yg di run ketika menggunakan persistent,
![image](https://github.com/golangid/candi/assets/3049864/47de295f-7dc9-489b-896c-15843306e89f)

Penggunaan nama field **interval** dan **key** sepertinya jadi issue di MariaDB,
 
https://github.com/golangid/candi/blob/29b06ef197cd1aa5e9491a8898562d77eeed4d69/codebase/app/task_queue_worker/persistent_sql.go#L35

https://github.com/golangid/candi/blob/29b06ef197cd1aa5e9491a8898562d77eeed4d69/codebase/app/task_queue_worker/persistent_sql.go#L80

Di MariaDB, jika kita mau pakai nama reserved word field, harus di dalam backtick (`).

Ada masukan @agungdwiprasetyo  & @golangid/candi-reviewer ?

**Comment by agungdwiprasetyo** [comment]
boleh juga, mungkin ditambahin option untuk override query untuk operationalnya, next release mungkin yak 😁

**Comment by ibnu-assaumi** [comment]
mungkin ga issue nya di naming column **interval** karena reserved words @agungdwiprasetyo ?

https://mariadb.com/kb/en/reserved-words/

**Comment by agungdwiprasetyo** [comment]
ayo saatnya showoff cuk @dimassantoso

**Comment by agungdwiprasetyo** [comment]
fixed in [v1.14.8](https://github.com/golangid/candi/releases/tag/v1.14.8), monggo sedot yg terbaru

**Comment by redzase** [comment]
yoi mantap

**Comment by isogram** [comment]
Goks. Thanks @agungdwiprasetyo .

**Comment by isogram** [comment]
bagian sini harusnya `formatMultiColumnName` 

https://github.com/golangid/candi/commit/090402129c9fd96b765ea53afec384d2322d0cf7#r114022654

https://github.com/golangid/candi/blob/090402129c9fd96b765ea53afec384d2322d0cf7/codebase/app/task_queue_worker/persistent_sql.go#L575

-- 

Tapi entah kenapa walaupun sudah dijadiin `formatMultiColumnName`, dapet error ginian, salah assign valuekah?
![image](https://github.com/golangid/candi/assets/3049864/f00a638c-2ec2-4acd-ac53-c4d76fdcd218)

**Comment by agungdwiprasetyo** [comment]
@isogram untuk yg `in memory queue` udah difix di [v1.14.9](https://github.com/golangid/candi/releases/tag/v1.14.9) yak, sedot lagi (pake go >=1.18 ya karena gw pakein generic).
sama table2 yg udah auto kebentuk pas running task queue worker (klo pake mysql/mariadb) didelete lagi aja, ada tambahan buat support utf8, kemaren lupa ditambahin 😂
