### ISSUE TITLE
documentations needed

### ISSUE THREAD

**Issue by ahmadfajar92** [golangid/candi#8]
Lord @agungdwiprasetyo mintul docs nya 😂

**Comment by isogram** [comment]
Wah ini... Minta di tampol. Dateng2 minta docs 🤣🏸

PR wa @ahmadfajar92, bantuin candi biar lengkap docsnya. 💪

**Comment by ahmadfajar92** [comment]
🤣 .. cuk @dimassantoso lengkapin docs nya disuruh lord @agungdwiprasetyo 😆

**Comment by agungdwiprasetyo** [comment]
waini nih kayanya ada sesuatu wkwkwk

**Comment by fathiraz** [comment]
lengkapin lahhh

**Comment by willy182** [comment]
> Lord @agungdwiprasetyo mintul docs nya 😂

Tau lu jar dateng2 minta docs. PR lah

**Comment by triadmoko** [comment]
untuk documentation bisa menggunakan ini mas. template hugo dari dot template.
repository aku sisip di sini mas. izin mau contribute juga mas. Paling tidak di documentationnya 

https://github.com/triadmoko/docs-candi

**Comment by agungdwiprasetyo** [comment]
> untuk documentation bisa menggunakan ini mas. template hugo dari dot template. repository aku sisip di sini mas. izin mau contribute juga mas. Paling tidak di documentationnya
> 
> https://github.com/triadmoko/docs-candi

mantab!
tuh @dimassantoso @ibnu-assaumi ikutan lah wkwk

**Comment by ibnu-assaumi** [comment]
in progress kak @ahmadfajar92 https://candi-docs-isogram.vercel.app/

tolong bantu tambah dan edit jg ya https://github.com/golangid/candi-docs 😄
